version: "3"

services:
    frontend:
        image: frontend-example
        container_name: exercise2.3-frontend
        ports:
            - 5000:5000
        environment:
            - API_URL=http://localhost:8000

    backend:
        image: backend-example
        container_name: exercise2.3-backend
        ports:
            - 8000:8000
        environment:
            - FRONT_URL=http://localhost:5000