FROM alpine as build-stage

WORKDIR /usr/app

RUN apk update && \
    apk add --no-cache git && \
    apk add --no-cache nodejs && \
    apk add --no-cache nodejs-npm && \
    git clone https://github.com/docker-hy/frontend-example-docker.git . && \
    npm install && \
    npm run build

FROM nginx
COPY --from=build-stage /usr/app/dist /usr/share/nginx/html