FROM ubuntu:16.04

WORKDIR /usr/app
COPY ./backend-example-docker .

RUN apt-get update && apt-get install curl -y && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt install -y nodejs && \
    apt-get purge -y --auto-remove curl && \ 
    rm -rf /var/lib/apt/lists/*

RUN useradd app && \
    chown -R app /usr/app

USER app

EXPOSE 8000

WORKDIR /app
CMD npm start