FROM ubuntu:16.04

WORKDIR /usr/app

RUN apt-get update && \
    apt-get install nodejs -y && \
    apt-get install npm -y && \
    apt-get install git -y && \
    git clone https://github.com/docker-hy/frontend-example-docker.git && \
    npm install && \
    npm install -g serve && \
    npm run build && \
    apt-get purge -y --auto-remove git && \ 
    apt-get purge -y --auto-remove npm && \ 
    rm -rf /var/lib/apt/lists/* && \
    ls | grep -v dist | xargs rm -R && \
    adduser -D app && \
    chown -R app /usr/app

USER app

EXPOSE 5000

CMD serve -s -l 5000 dist